theme = "hyde"
googleAnalytics = "UA-173443140-1"

baseURL = "https://lostinthegc.com/"
languageCode = "en-us"
title = "Sergio Tapia"
paginate = 15

[params]
  layoutReverse = false
  author = "Sergio Tapia"
  description = "Writing about Elixir, Nim and empowering engineering teams to do great things. VP of Engineering at Papa."



