theme = "hyde"
googleAnalytics = "Your tracking code"

baseURL = "https://sergiodev.netlify.com/"
languageCode = "en-us"
title = "Sergio Tapia Personal Blog"
paginate = 15

[params]
  layoutReverse = true
  author = "Sergio Tapia"
  description = "Lead / Senior Software Engineer Elixir | Rails | React | Javascript | I work out of Miami, USA with startups and mid-size companies to get their product off the ground. Send me an email if you want to meet up or hop on a call."
  [[params.social]]
    name = "github"
    url = "https://github.com/sergiotapia"
  [[params.social]]
    name = "send"
    url = "mailto:sergiotapia@outlook.com"



