theme = "hyde"
googleAnalytics = "UA-154849727-1"

baseURL = "https://sergio.dev/"
languageCode = "en-us"
title = "Sergio Tapia"
paginate = 15

[params]
  layoutReverse = false
  author = "Sergio Tapia"
  description = "Writing about Elixir, Scalability, Team Growth and Management. Director of Engineering @ Papa. sergiotapia<at>outlook.com"



